# Generated by Django 5.0.2 on 2024-02-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_market", "0002_remove_order_products_orderitem_total_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number_of_order",
            field=models.CharField(default="8a6YYfHGA97skT", max_length=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
