# Generated by Django 5.0.2 on 2024-03-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_market", "0003_alter_order_number_of_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductHistory",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="super_market.product",
                    ),
                ),
            ],
            bases=("super_market.product",),
        ),
        migrations.AlterField(
            model_name="order",
            name="number_of_order",
            field=models.CharField(
                default="tph6yax4k8vdb9", max_length=50, verbose_name="الكود"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="سعر البيع"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="الكمية"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="سعر الكمية",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="باركود"
            ),
        ),
    ]
