# Generated by Django 5.0.2 on 2024-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_market", "0004_producthistory_alter_order_number_of_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number_of_order",
            field=models.CharField(
                default="a0o7t5xqdh8108", max_length=50, verbose_name="الكود"
            ),
        ),
    ]
