# Generated by Django 5.0.3 on 2024-04-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_market", "0006_order_total_oreders_alter_order_number_of_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number_of_order",
            field=models.CharField(
                default="fgdltcgkoalnik", max_length=50, verbose_name="الكود"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="Quantity",
            field=models.PositiveBigIntegerField(verbose_name="الكميه"),
        ),
    ]
