# Generated by Django 5.0.3 on 2024-04-14 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("super_market", "0007_alter_order_number_of_order_alter_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="number_of_order",
        ),
    ]
